### ISSUE TITLE
[UI] Bottom App Bar 적용하기

### ISSUE THREAD

**Issue by ggujangi** [ggujangi/ggu.share#1]
### 앱 하단 메뉴 생성하기

**github** : https://github.com/material-components/material-components-android/blob/master/docs/components/BottomAppBar.md
**material3** : https://m3.material.io/components/bottom-app-bar/guidelines
**아이콘** : https://fonts.google.com/icons?icon.platform=android

메인 메뉴 : 설정, 중요, 선택 모드 
서브 메뉴 : 삭제, 다운로드, 공유하기

**Comment by Sanghun-Lee** [comment]
지켜보겠습니다

**Comment by ggujangi** [comment]
BottomAppBar 생성 완료

![Screenshot_20230105_020457](https://user-images.githubusercontent.com/25583321/210610167-1ae1c6e2-6625-4fb3-b53d-c7705c1316fb.png)
